#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define Menu_MDI_Main                           102
#define Menu_MDI_Child                          104
#define LEA_Icon                                114
#define Toolbar_BMP                             123
#define Folders_BMP                             124
#define Backup_none_button                      40000
#define IDM_Go_to_line                          40001
#define IDM_Open_Project                        40002
#define IDM_Previous_bookmark                   40003
#define IDM_Toggle_bookmark                     40004
#define IDM_Copy                                40005
#define IDM_Cut                                 40006
#define IDM_Find_Next                           40007
#define IDM_Paste                               40008
#define IDM_Duplicate                           40009
#define IDM_Check_syntax                        40010
#define IDM_New_File                            40011
#define IDM_Build_and_run                       40012
#define IDM_Build                               40013
#define IDM_Compile_single                      40014
#define IDM_ABOUT                               40015
#define IDM_Open_File                           40016
#define IDM_HAC_Mode                            40017
#define IDM_GNAT_Mode                           40018
#define IDM_Studio_view                         40019
#define IDM_Notepad_view                        40020
#define IDM_Copy_Messages                       40021
#define Replace_all_button                      40021
#define Close_search_box                        40022
#define IDM_Undo                                40023
#define Version_label                           40024
#define Whole_word                              40025
#define Backup_bak_button                       40026
#define GNAT_URL                                40028
#define IDM_Save_All                            40029
#define IDM_Unselect_all                        40030
#define GNAT_Version                            40031
#define IDM_Save_File                           40032
#define Right_margin_edit_box                   40033
#define GNAVI_URL                               40034
#define Group_color_theme                       40035
#define IDM_Redo                                40036
#define IDM_TEST_ARCHIVE                        40038
#define ResEdit_URL                             40039
#define IDM_Save_As                             40040
#define IDM__QUIT                               40041
#define IDM_Close                               40042
#define IDM__RECOMPRESS_ARCHIVE                 40043
#define IDM_EXTRACT                             40044
#define IDM_General_options                     40045
#define IDM_Find                                40046
#define IDM_MRU_2                               40049
#define IDM_MRU_3                               40050
#define IDM_MRU_4                               40051
#define IDM_MRU_5                               40052
#define IDM_MRU_6                               40053
#define IDM_MRU_7                               40054
#define IDM_MRU_8                               40055
#define IDM_MRU_9                               40056
#define IDM_WINDOW_CASCADE                      40057
#define IDM_WINDOW_TILE_HORIZONTAL              40058
#define IDM_WINDOW_TILE_VERTICAL                40059
#define IDM_WINDOW_CLOSE_ALL                    40060
#define IDM_UPDATE_ARCHIVE                      40061
#define IDM_Quick_Help                          40062
#define IDM_Web                                 40063
#define IDM_Select_all                          40064
#define IDM_MRU_1                               40065
#define IDM_Indent                              40066
#define IDM_Unindent                            40067
#define IDM_Comment                             40068
#define IDM_Uncomment                           40069
#define IDM_Show_special_symbols                40070
#define IDM_Find_Previous                       40071
#define IDM_Run                                 40072
#define ZipAda_URL                              40073
#define ZipAda_Version                          40074
#define HAC_Version                             40075
#define Tab_width_edit_box                      40076
#define HAC_URL                                 40077
#define IDM_Next_bookmark                       40078
#define Model_find_box                          40079
#define Model_replace_box                       40080
#define Line_value_box                          40081
#define Match_case                              40082
#define Copyright_label                         40083
#define Group_Backup                            40084
#define Find_next_button                        40085
#define Find_previous_button                    40086
#define AZip_URL                                40087
#define Find_all_button                         40088
#define Replace_and_find_next_button            40089
#define Color_theme_list_box                    40090
#define Indentation_edit_box                    40091
#define Ada_file_extension_edit_box             40092
#define String_Prompt_Edit_Box                  40093
#define String_Prompt_Label                     40094
