#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define Menu_MDI_Main                           102
#define Menu_MDI_Child                          104
#define LEA_Doc_Icon                            112
#define LEA_Icon                                114
#define Toolbar_BMP                             123
#define Folders_BMP                             124
#define Binoculars_Icon                         132
#define IDM__NEW_ARCHIVE                        40000
#define IDM_Open_File                           40001
#define IDM_MRU_1                               40002
#define IDM_Unselect_all                        40002
#define IDM__ABOUT                              40003
#define IDM_TEST_ARCHIVE                        40004
#define IDM__QUIT                               40005
#define IDM__RECOMPRESS_ARCHIVE                 40006
#define IDM_EXTRACT                             40007
#define IDM_FIND_IN_ARCHIVE                     40008
#define IDM__FLAT_VIEW                          40010
#define IDM__TREE_VIEW                          40011
#define IDM_MRU_2                               40012
#define IDM_MRU_3                               40013
#define IDM_MRU_4                               40014
#define IDM_MRU_5                               40015
#define IDM_MRU_6                               40016
#define IDM_MRU_7                               40017
#define IDM_MRU_8                               40018
#define IDM_MRU_9                               40019
#define IDM_WINDOW_CASCADE                      40020
#define IDM_WINDOW_TILE_HORIZONTAL              40021
#define IDM_WINDOW_TILE_VERTICAL                40022
#define IDM_WINDOW_CLOSE_ALL                    40023
#define IDM_Delete_selected                     40026
#define IDM_ADD_FILES                           40027
#define IDM_UPDATE_ARCHIVE                      40028
#define IDM__CLOSE_ARCHIVE                      40029
#define IDM_Properties                          40032
#define IDM_Quick_Help                          40035
#define IDM_Web                                 40036
#define IDM_SAVE_ARCHIVE_AS                     40037
#define IDM_Select_all                          40038
